name = "TME_Nudos"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TMENudos"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "2df2f0150c275ad53cb3c90f7c98ec15a56a1a67"

[[lean_lib]]
name = "TMENudos"

[[lean_exe]]
name = "check_r2"
root = "check_r2"
